sonar.projectKey=AnastasiyaBogdanova_frontend-project-46
sonar.organization=anastasiyabogdanova

sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.js

sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js

sonar.javascript.file.suffixes=.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/__fixtures__/**