sonar.projectKey=AnastasiyaBogdanova_frontend-project-46
sonar.organization=anastasiyabogdanova

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.js
sonar.coverage.exclusions=**/*.test.js,**/__fixtures__/**
sonar.exclusions=**/node_modules/**,**/coverage/**